<a href="https://colab.research.google.com/github/ddopazo92/Introduccion_datascience_diego_dopazo/blob/main/Arrays%20parte%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [155]:
import numpy as np

contenido = np.arange(0,20)

filas_columnas = np.array(contenido)

print(filas_columnas)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [49]:
import numpy as np
array_secuencial = np.arange(0,10,2) ##los primeros dos numeros marcan el rango elegido, y el 2 indica que los numeros elegidos tendras una diferencia de dos
array_aleatorio = np.random.randint(0,10, size=(5,5)) ##elige numeros aleatorios dentro del rango elegido, y el tamaño de la matriz(tabla) va definida en size
print (array_secuencial)
print (array_aleatorio)
print(array_secuencial.dtype)

[0 2 4 6 8]
[[5 7 3 7 1]
 [3 6 4 4 4]
 [2 3 3 3 7]
 [8 7 3 2 2]
 [2 3 4 7 1]]
int64


In [51]:
import numpy as np

palabras_array = np.array(["Lunes","martes","miercoles","jueves","viernes","sabado","domingo"])

palabras_array = np.random.choice(palabras_array, size=(5,7)) ##el contenido de palabras_array con random.choice hace que elija de forma aleatoria el orden del contenido del array

print(palabras_array[1,1]) ##el primer numero elige en este caso la primera fila 1 de 5, creada en el random.choice, y el segundo elige la posicion del valor requerido, en este caso el 1 inidca la segunda posicion
print(palabras_array.dtype) ##tipo de dato utilizdo en el array
print(palabras_array.shape) ##como se omprende tu array, filas/columnas
print(palabras_array.size)  ##cuantos espacios son utilizados, en el caso de las cadenas de texto, cuenta cada caracter eso incluye los espacios

martes
<U9
(5, 7)
35


### **Crear un array que calcule el promedio**

In [163]:
import numpy as np

array_numeros_random = np.random.randint(0,100,size=9)

promedio = np.mean(array_numeros_random)

print(array_numeros_random)
print("el promedio del array es:",promedio)

[27 63 89 13 57 88 83 66 24]
el promedio del array es: 56.666666666666664


**Ubicar el elemento central de un array**

In [164]:
import numpy as np

mediana = np.median(contenido)

print(mediana)

56.666666666666664
