<a href="https://colab.research.google.com/github/ddopazo92/Introduccion_datascience_diego_dopazo/blob/main/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

contenido = np.array([1,2,3,4,5])

filas_columnas = np.full(2,3)

print(filas_columnas)

[3 3]


In [26]:
import numpy as np
array_secuencial = np.arange(0,10,2) ##los primeros dos numeros marcan el rango elegido, y el 2 indica que los numeros elegidos tendras una diferencia de dos
array_aleatorio = np.random.randint(0,10, size=(5,5)) ##elige numeros aleatorios dentro del rango elegido, y el tamaño de la matriz(tabla) va definida en size
print (array_secuencial)
print (array_aleatorio)

[0 2 4 6 8]
[[2 1 8 3 8]
 [6 2 3 7 0]
 [7 9 5 2 0]
 [2 5 2 0 4]
 [9 7 1 0 0]]
