<a href="https://colab.research.google.com/github/ddopazo92/Introduccion_datascience_diego_dopazo/blob/main/Matrices%20y%20algebra%20%20lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CLASE 03**

# Numpy

In [ ]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])



print(a + b)
print(a * 2)
print(b**2) ##potencia

[11 22 33]
[20 40 60]
[1 4 9]


In [ ]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]]) ##un array con dos filas, 1 y 2 en la primera, 3 y 4 en la segunda

print(A.T) ## T = transpuesta que quiere decir que la fila 0 (en este caso 1 y 2)
           ## se convierte en columna entonces la fila 0 pasa a ser 1 y 3 porque el 2 queda por debajo del 1, siendo ahora una columna

print(np.linalg.inv(A))

B = np.array([[2, 6],
              [0, 8]]) ## producto matricial es el primer elemento de la fila A (1) por el primer elemento de la primera columna B (2) + el segundo elemento del primera fila  A(2)
                      ## por segundo elemento de la primera columna de B(6), despues es el primer elemento de la fila (A) multiplicado por el primer elemento de la segunda columna B (6)
                      ## sumado a el segundo elemento de la primera fila (A) = 2 multiplicado por el segundo elemento de la segunda columna B, y despues realiza lo mismo con la fila dos del array A

print(np.dot(A, B))

[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 2 22]
 [ 6 50]]
